### ISSUE TITLE
Journal Entries and Day Entries

### ISSUE THREAD

**Issue by elanosilveira** [monicahq/monica#3408]
**Describe the bug**
Journal entries are being added below the previous day of the Day(rate your day feature) entries.
If I add a journal entry on 12/30/2019, it will be added below the Day entry(rate your day feature) 12/29/2019, not 12/30/219 as it should be.

**Screenshots**
![journal](https://i.imgur.com/0GMGrGq.png)
https://i.imgur.com/0GMGrGq.png
**Which version are you using:**
 - A server I maintain (v2.15.2)

**Additional context**
-

**Comment by asbiin** [comment]
This might have been fixed, can you confirm?

**Comment by weaversam8** [comment]
This ordering is still broken. I added a "rate your day" a few days ago and it still displays above activity entries for a day. This is on version v3.0.1.

![image](https://user-images.githubusercontent.com/2546219/117501315-dcfe6680-af4b-11eb-9af4-55a839a571d2.png)

**Comment by OrinSafko** [comment]
@asbiin I can confirm that I'm still seeing this issue as well. I'm using the hosted version of Monica.
