### ISSUE TITLE
No reminders e-mails

### ISSUE THREAD

**Issue by peetersdaan** [monicahq/monica#4178]
Hi all,

Currently, I am running MonicaHQ on my Synology DS418:Play (through Portainer). I have managed to set up the SMTP server, which works (i.e. I receive e-mails when inviting users to the system). However, when setting a reminder for a certain person, I do not get any e-mails. I have already tried changing the time that the system sends the reminders. 

Monica Version: 2.18.0
`environment:
      # generate with `pwgen -s 32 1` for instance:
      - APP_KEY=
      - DB_HOST=db
      - DB_DATABASE=monica_db
      - DB_USERNAME=monica-user
      - DB_PASSWORD=secret
      - MAIL_MAILER=smtp
      - MAIL_HOST=smtp.gmail.com
      - MAIL_PORT=587
      - MAIL_ENCRYPTION=tls
      - MAIL_USERNAME=
      - MAIL_PASSWORD=
      - MAIL_FROM_ADDRESS=
      - MAIL_FROM_NAME="Monica Personal CRM"`

**Comment by peetersdaan** [comment]
I've managed to make it work to add - CRON_LEGACY=true to the environment of my docker-compose.yml. However, as it is not ideal to run cron in the container I want to install supervisor.
https://github.com/monicahq/monica/tree/master/scripts/docker/.examples

Unfortunately, I am not able to set up supervisor. Could anyone assist me (even for a small fee) with this?

**Comment by deferredreward** [comment]
I also have email configured properly (it seems, as I get sign up mails and when I run the new test command it works), but don't get reminder emails. I'm running in a VPS Ubuntu 18, standard linux setup. Happy to submit any config or logs by request.

**Comment by asbiin** [comment]
@deferredreward did you try using supervisord like in the example section? https://github.com/monicahq/monica/tree/master/scripts/docker/.examples/supervisor

**Comment by kingcc** [comment]
I have same issue, has there been any progress since the last reply?

**Comment by zeezhao** [comment]
Hi - same issue here - not getting reminders. I am running a self-hosted v2.19.1

I have tested email using: php artisan monica:test-email
and that works.

But daily and birthday reminders not working (i.e. no emails received)  via running:
 php artisan schedule:run

Please - any ideas? Thanks

**Comment by meijbaard** [comment]
Is there a possibility you're user_id is changed? I had the same issue and this came because of the fact after upgrading my new user account had id 5 instead if id 1. So the job couldn't find the right emailaddress, because id 1 wasn't in de database available anymore.

I fixed this to do un update in the table reminder_outbox and changed the user_id;

**Comment by zeezhao** [comment]
@meijbaard, thanks for the tip - it now works! I fixed the users table so that it matches accounts & reminder_outbox tables.
I guess a bug in the upgrade... Thanks for your help!

**Comment by peetersdaan** [comment]
> @meijbaard, thanks for the tip - it now works! I fixed the users table so that it matches accounts & reminder_outbox tables.
> I guess a bug in the upgrade... Thanks for your help!
> 
> edit:
> The only reminders now not received are the "Stay in touch" reminders I had set to daily. But this may be a separate issue...

@zeezhao, recently I reinstalled Monica, however I am also still facing this issue.

**Comment by zeezhao** [comment]
@peetersdaan - not getting any reminders at all? If so, as suggested above, make sure the id=1 in user table exists and aligns with account table. Do do that I had to do manual updates and actually some tables like reminder table to avaoid index violation errors. But since it is just a test installation for me, it did not matter.

If it is just the "stay in touch" reminders, I have not figured that out yet. I cant even see them stored in any table. so that may be a bug.

It is also crucial to make sure that monica can send mails anyway using this command, which can send a test emenail to an address of your choice:
php artisan monica:test-email

If that does not work, then your monica environment needs to be properly setup for emails.

Hope this helps...

**Comment by peetersdaan** [comment]
@zeezhao, I just reinstalled Monica completely. 

php artisan monica:test-email works, however, php artisan send:stay_in_touch not.

**Comment by meijbaard** [comment]
This command only will send reminders that are in the range of 7/30 days I guess. So if there are no reminders to be send, then this will give no output.

You can check your database table reminders_outbox, to see if everything is there.

**Comment by zeezhao** [comment]
What I also found is that the "stay in touch" reminders do not always work.... I can't even see where they are stored i.e. "stay in touch" reminders. 
Normal reminders exist in the reminder_outbox table.

**Comment by iloveitaly** [comment]
@zeezhao the stay_in_touch data is stored on two columns on the contact database.

I ran into issues here as well. [Here's the docker config](https://github.com/monicahq/docker/pull/49) that fixed the issue on my raspberry pi.

**Comment by onetrickwolf** [comment]
Hey having this issue too. I am running docker with `supervisord` and the email test works as well as forget password emails but it seems like general reminders and stay in touch reminders do not.

I tried setting a bunch of reminders organically and never got them after a few days besides them being set to send daily. After that I tried running the commands directly.

Running `php artisan send:stay_in_touch` does nothing no output and no emails.

Running `php artisan schedule:run` gives "No scheduled commands are ready to run."

Looking at the database it looks like my user ID is 1 and this is a fresh install so don't think it's that issue. I see reminders in the outbox.

I see the stay in touch trigger dates in the contacts table and tried setting the trigger to a time in the past and running `php artisan send:stay_in_touch` but all it does is update the trigger time to the next day but does not actually send the email. Not in spam and checking AWS SES does not show any emails sent.

If anyone has any ideas on how to further debug let me know I have been playing around with it for a few days and am stumped.

**Comment by onetrickwolf** [comment]
Kind of odd but I changed nothing since my last post but left the instance running and received one stay in touch reminder today. Funny though I have a stay in touch reminder set for many people daily and only got it for one person today and this is after several days have passed. I also set up some manual reminders that have still never sent.

Logs don't look any different from last couple of days where nothing sent, just keep seeing stuff like this:

```crond: file www-data:
crond:  line php /var/www/html/artisan schedule:run -v
crond: wakeup dt=60
crond: file www-data:
crond:  line php /var/www/html/artisan schedule:run -v
crond: wakeup dt=60
crond: file www-data:
crond:  line php /var/www/html/artisan schedule:run -v
crond:  job: 0 php /var/www/html/artisan schedule:run -v
crond: child running /bin/bash
crond: USER www-data pid 2565 cmd php /var/www/html/artisan schedule:run -v
crond: wakeup dt=10
[2021-07-15 17:00:11][52] Processing: App\Jobs\StayInTouch\ScheduleStayInTouch
[2021-07-15 17:00:11][52] Processed:  App\Jobs\StayInTouch\ScheduleStayInTouch
[2021-07-15 17:00:11][53] Processing: App\Jobs\StayInTouch\ScheduleStayInTouch
[2021-07-15 17:00:11][53] Processed:  App\Jobs\StayInTouch\ScheduleStayInTouch
[2021-07-15 17:00:12][54] Processing: App\Notifications\StayInTouchEmail
[2021-07-15 17:00:14][54] Processed:  App\Notifications\StayInTouchEmail
crond: wakeup dt=50
crond: file www-data:
crond:  line php /var/www/html/artisan schedule:run -v
crond: wakeup dt=60
crond: file www-data:
crond:  line php /var/www/html/artisan schedule:run -v```

Very odd problem if anyone has any ideas. My network and server are all pretty normal and other docker containers aren't have any problem.

**Comment by onetrickwolf** [comment]
Okay I guess final update from me but just finding reminders really inconsistent but they seem to be working now? Not sure if there are special rules for reminders being sent out or something (if you visit the person's page do you not get a stay in touch reminder or something?) but I am getting enough now for it to be usable after a few days.

I have two test instances of Monica running with pretty much the exact same people and reminders. One is a Heroku app and one is running in Docker on a local server.

The local instance did not send reminders out for the first day or two and now is doing it consistently. The Heroku app gives me reminders on and off...I assume this might have something to do with Heroku putting unused apps to sleep and the scheduler not being able to wake it up properly or something.

Anyway the local instance is working fine enough for my liking now. Wish I could help other people having this problem but I honestly did not change anything, just left it running for a few days.

**Comment by b3nd1k** [comment]
> Okay I guess final update from me but just finding reminders really inconsistent but they seem to be working now? 

Did you do anything to get it working @onetrickwolf? I have been running Monica for a few months, but have not been able to get it working. I'm running Monica in Docker on my server. `php artisan monica:test-email` works, but nothing else.

**Comment by onetrickwolf** [comment]
@b3nd1k unfortunately I have no idea what I did. I tried a bunch of different things and it seemed like none of it worked then suddenly was just working some days later after changing nothing. It worked consistently until about last month and now again I have no idea why it's not working. It doesn't seem to line up with any updates or anything specific I changed. I have this issue across different types of installations and different email services etc. Checked spam folder etc.

I haven't dug as deep as I could though.

**Comment by meijbaard** [comment]
Same issue here. Fresh installation, no notifications.

DId a clean install today with a new import of only contacts. Just looking if this is working.

**Comment by peetersdaan** [comment]
Just a small update, in the past I made it work by using the [apache supervisor](https://github.com/monicahq/docker/tree/master/.examples/supervisor/apache) and by placing the ./app in the correct docker folder on my Synology.

````
version: "3.4"

services:
  app:
    build: ./app
    image: monica-app
    depends_on:
      - db
    environment:
      - APP_KEY=
      - DB_HOST=db
      - TZ=Amsterdam/Europe
      - MAIL_MAILER=smtp
      - MAIL_HOST=smtp.gmail.com
      - MAIL_PORT=587
      - MAIL_ENCRYPTION=tls
      - MAIL_USERNAME=
      - MAIL_PASSWORD=
      - MAIL_FROM_ADDRESS=
      - MAIL_FROM_NAME="Monica Personal CRM"
      - APP_URL=
      - APP_ENV=
      - QUEUE_CONNECTION=database
      - PUID=
      - GUID=
    ports:
      - 8080:80
    volumes:
      - /volume1/docker/monica/data:/var/www/html/storage
    restart: always

  db:
    image: mysql:5.7
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE=
      - MYSQL_USER=
      - MYSQL_PASSWORD=
    volumes:
      - /volume1/docker/monica/db:/var/lib/mysql
    restart: always

**Comment by zeezhao** [comment]
Same issue here on a fresh installation. Reminders on an old one stopped too a while back... I have left it for now.

> Same issue here. Fresh installation, no notifications.
> 
> DId a clean install today with a new import of only contacts. Just looking if this is working.

**Comment by meijbaard** [comment]
I did that also. It is working. I now get them twice :) Let me know if you face the same.

**Comment by zeezhao** [comment]
I ran it manually using: php artisan schedule:run

and it now works again.

I noticed that it is very sensitive to the "Time of the day reminders will be sent " setting. 

If for any reason cron did not work and you try and run it manually after the time setting has passed, it may not work. I would have expected code to still run provided it has not run at all for the day.

**Comment by Fardenz** [comment]
I relate to this issue, by running the docker with the env flag `CRON_LEGACY=true` or running the `php artisan send:stay_in_touch` script it seems like the stay in touch dates are updated, but no emails are sent. I do get the export complete and forgot password emails.

![image](https://github.com/monicahq/monica/assets/28675332/293c1b44-4d2d-48d9-999f-6bb525d0fd1e)

**Comment by chevdor** [comment]
Same issue here. `php artisan monica:test-email` works fine.
I tried the CRON_LEGACY option, I tried to run a second container running cron.sh, I tried changing the delivery time, I checked accounts id... other than `php artisan monica:test-email`, no email is even sent.

**Comment by AlexIn-Tech** [comment]
> @zeezhao the stay_in_touch data is stored on two columns on the contact database.
> 
> I ran into issues here as well. [Here's the docker config](https://github.com/monicahq/docker/pull/49) that fixed the issue on my raspberry pi.

Hello everyone, 

I can confirm the following solution works great. I am running it on Unraid as a docker stack. I use adminer to manage the DB but you can remove it if you don't need it.  Here is my docker-compose file and my .env file : 

**docker-compose file**
```
version: "3.9"

services:
  app:
    image: monica
    env_file: .env
    depends_on:
      - db
    ports:
      - 8181:80
    volumes:
      - /mnt/user/appdata/monica-webapp:/var/www/html/storage
    restart: always

  cron:
    image: monica
    env_file: .env
    restart: always
    volumes:
      - /mnt/user/appdata/monica-webapp:/var/www/html/storage
    command: cron.sh
    depends_on:
      - db

  db:
    image: mariadb:11
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE=monica
      - MYSQL_USER=XXXXXXXXXXXXXXXXX
      - MYSQL_PASSWORD=XXXXXXXXXXXXXXXXXXX
    volumes:
      - /mnt/user/appdata/monica-db:/var/lib/mysql
    restart: always

  adminer:
    image: adminer
    restart: always
    ports:
      - 8282:8080
```

**.env file :** I don't use the things in comments but you could if you wish. 
```
APP_ENV=local
APP_DEBUG=false
# The encryption key. Must be 32 characters long exactly.
# Use `echo -n 'base64:'; openssl rand -base64 32` to generate a random key.
APP_KEY=XXXXXXXXXXXXXXX

# The URL of your application.
# APP_URL=http://localhost

# Set trusted proxy IP addresses.
# To trust all proxies that connect directly to your server, use a "*".
# APP_TRUSTED_PROXIES=

# Database information
# DB_CONNECTION=mysql
DB_HOST=db
DB_DATABASE=monica
DB_USERNAME=XXXXXXXXXXXX
DB_PASSWORD=XXXXXXXXXXXXXXXXXXXXX

# Mail credentials used to send emails from the application.
MAIL_DRIVER=smtp
MAIL_HOST=smtp.yourmailservice.com
MAIL_PORT=587
MAIL_USERNAME=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
MAIL_PASSWORD=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
MAIL_ENCRYPTION=tls
# Outgoing emails will be sent with these identity
MAIL_FROM_ADDRESS=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
MAIL_FROM_NAME=Monica

LOG_CHANNEL=stderr

CACHE_DRIVER=database
SESSION_DRIVER=database
QUEUE_DRIVER=sync
```

I hope it helps 🤓

**Comment by chevdor** [comment]
I think the main issue overall is the lack of proper logging of the errors.
Many people run the `php artisan monica:test-email` and it works while the rest does not.
There should be a log showing what is done, that would help people realize it is the wrong email or user, for instance.

As you did @AlexIn-Tech I did add a container running `cron.sh`, after realizing that running the main container was not enough.

A solution to that issue would be the the last cron run is show somehow with some `php artisan monica:cron-stats`.
If the last run is `never`, it would be clear that the user does not run cron with one of the available strategies. If the last run was 1h ago but no email was sent, the user can dig further in the logs.

**Comment by rama31244** [comment]
> > @zeezhao the stay_in_touch data is stored on two columns on the contact database.
> > I ran into issues here as well. [Here's the docker config](https://github.com/monicahq/docker/pull/49) that fixed the issue on my raspberry pi.
> 
> Hello everyone,
> 
> I can confirm the following solution works great. I am running it on Unraid as a docker stack. I use adminer to manage the DB but you can remove it if you don't need it. Here is my docker-compose file and my .env file :
> 
> **docker-compose file**
> 
> ```
> version: "3.9"
> 
> services:
>   app:
>     image: monica
>     env_file: .env
>     depends_on:
>       - db
>     ports:
>       - 8181:80
>     volumes:
>       - /mnt/user/appdata/monica-webapp:/var/www/html/storage
>     restart: always
> 
>   cron:
>     image: monica
>     env_file: .env
>     restart: always
>     volumes:
>       - /mnt/user/appdata/monica-webapp:/var/www/html/storage
>     command: cron.sh
>     depends_on:
>       - db
> 
>   db:
>     image: mariadb:11
>     environment:
>       - MYSQL_RANDOM_ROOT_PASSWORD=true
>       - MYSQL_DATABASE=monica
>       - MYSQL_USER=XXXXXXXXXXXXXXXXX
>       - MYSQL_PASSWORD=XXXXXXXXXXXXXXXXXXX
>     volumes:
>       - /mnt/user/appdata/monica-db:/var/lib/mysql
>     restart: always
> 
>   adminer:
>     image: adminer
>     restart: always
>     ports:
>       - 8282:8080
> ```
> 
> **.env file :** I don't use the things in comments but you could if you wish.
> 
> ```
> APP_ENV=local
> APP_DEBUG=false
> # The encryption key. Must be 32 characters long exactly.
> # Use `echo -n 'base64:'; openssl rand -base64 32` to generate a random key.
> APP_KEY=XXXXXXXXXXXXXXX
> 
> # The URL of your application.
> # APP_URL=http://localhost
> 
> # Set trusted proxy IP addresses.
> # To trust all proxies that connect directly to your server, use a "*".
> # APP_TRUSTED_PROXIES=
> 
> # Database information
> # DB_CONNECTION=mysql
> DB_HOST=db
> DB_DATABASE=monica
> DB_USERNAME=XXXXXXXXXXXX
> DB_PASSWORD=XXXXXXXXXXXXXXXXXXXXX
> 
> # Mail credentials used to send emails from the application.
> MAIL_DRIVER=smtp
> MAIL_HOST=smtp.yourmailservice.com
> MAIL_PORT=587
> MAIL_USERNAME=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
> MAIL_PASSWORD=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
> MAIL_ENCRYPTION=tls
> # Outgoing emails will be sent with these identity
> MAIL_FROM_ADDRESS=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
> MAIL_FROM_NAME=Monica
> 
> LOG_CHANNEL=stderr
> 
> CACHE_DRIVER=database
> SESSION_DRIVER=database
> QUEUE_DRIVER=sync
> ```
> 
> I hope it helps 🤓

Hi I also run monica on unraid but via the container template rather than using docker compose. Can I modify the template in the edit screen to implement this solution? Or do i need to use docker compose? Thanks

**Comment by Matthias-vdE** [comment]
Just wanted to chime in that I have the exact same issue. The test-mail arrives just fine, but making a test notification and then manually trying to trigger it does not send any e-mails. Docker compose file:

```
services:
  app:
    image: monica
    depends_on:
      - db
    ports:
      - 7080:80
    environment:
      - APP_KEY=base64:mySuperSecretKey=
      - DB_HOST=db
      - DB_USERNAME=usermonica
      - DB_PASSWORD=mySuperSecretDBPassword
      - APP_ENV=production
      - APP_URL=monica.mydomain.org
      - MAIL_DRIVER=smtp
      - MAIL_HOST=smtp.gmail.com
      - MAIL_PORT=587
      - MAIL_USERNAME=mygmail@gmail.com
      - MAIL_PASSWORD=myemailpassword
      - MAIL_ENCRYPTION=tls
      # Outgoing emails will be sent with these identity
      - MAIL_FROM_ADDRESS=mygmail@gmail.com
      - MAIL_FROM_NAME=Monica
    volumes:
      - monica_data:/var/www/html/storage
    restart: always

  db:
    image: mariadb:11
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE=monica
      - MYSQL_USER=usermonica
      - MYSQL_PASSWORD=mySuperSecretDBPassword
    volumes:
      - monica_mysql:/var/lib/mysql
    restart: always

volumes:
  monica_data:
  monica_mysql:
```

**Comment by socal0001** [comment]
Confirming that adding the cron image also works with v5, here is mine, not the entrypoint vs the command in the version above.  

  cron:
    image: monica:5.0-apache
    container_name: monica_app5_cron
    volumes:
      - monica_data:/var/www/html/storage
    networks:
      - internal
    environment:
      [redacted]
    entrypoint: /usr/local/bin/cron.sh
    depends_on:
      - db
