### ISSUE TITLE
Can't Upload Photo as Avatar

### ISSUE THREAD

**Issue by rasulkireev** [monicahq/monica#6915]
I'm using Beta Version of Monica (https://beta.monicahq.com).

I can't upload photo as avatar. I'm able to select the file and preview it. Once I click "Done" the modal closes but nothing happens. I tried reloading the page and uploading a few times. Still doesn't work.

I'm on Version v5.0.0-beta.2 — commit [eef206d](https://github.com/monicahq/monica/commit/eef206dba5c92fd1ec5dacfc2f72fc9a087b7a0e).

No rush, thanks for taking a look.

**Comment by rasulkireev** [comment]
Here is the console log for the image upload:
![CleanShot 2023-10-05 at 10 43 56](https://github.com/monicahq/monica/assets/8257474/70902031-e534-4af3-94fa-038f81e2cd50)

**Comment by asbiin** [comment]
This has been fixed by #6942

**Comment by pkuehne** [comment]
This is still happening, but with a different CORS error now:

![image](https://github.com/monicahq/monica/assets/4983974/62559ac2-cf17-4410-95cf-f7544b18de37)
