### ISSUE TITLE
Github login broken

### ISSUE THREAD

**Issue by sylvainmetayer** [monicahq/monica#7148]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/monicahq/monica/issues?q=is%3Aopen+is%3Aissue+label%3Abug) _(I've searched it)_.
- [X] I agree to follow Monica's [Code of Conduct](https://github.com/monicahq/monica/blob/main/CODE_OF_CONDUCT.md).

### Bug description

Cannot login via Github 

### Steps to reproduce

1. Go to [https://beta.monicahq.com/login](https://beta.monicahq.com/login)
2. Click on Github login
3. See a 500 HTTP error

![image](https://github.com/monicahq/monica/assets/8873695/bcf705f8-2202-4668-a4a7-f39519af87b3)
![image](https://github.com/monicahq/monica/assets/8873695/60ad7bb6-710b-4338-b358-f0b2900a559b)

### Expected behavior

Login via Github

### Environment

beta.monicahq.com (v5 a.k.a chandler version or main branch)

### Installation method

None

### Web server

None

### Database engine version

None

**Comment by chris-est** [comment]
I am getting "419 Page Expired", on reload i am redirected to the login page.

**Comment by sylvainmetayer** [comment]
Seems fixed now, I'm closing the issue.

**Comment by debuglevel** [comment]
Just tried to create an account. Just threw Error 419.

**Comment by chris-est** [comment]
Login is also broken, i get "419 Page Expired" again.
Maybe try again in a few days, seems the beta version is still buggy sometimes!?
