### ISSUE TITLE
Change Email "From" Attribute

### ISSUE THREAD

**Issue by johnriley** [monicahq/monica#977]
All emails appear they are personally from Regis... How about making it Monica HQ versus Regis.

**Comment by djaiss** [comment]
Done 😀

**Comment by asbiin** [comment]
This is still the case on app.monicahq.com

**Comment by djaiss** [comment]
@asbiin It is not. It's set to `Monica HQ` in production. Are you sure?

**Comment by asbiin** [comment]
I still get reminders from 'Regis from Monica'. Don't you?

**Comment by johnriley** [comment]
Yep. I do as well

**Comment by djaiss** [comment]
I don't understand.
In my `.env`, I have `MAIL_FROM_NAME='Monica HQ'`.
There is not a single instance in the codebase where we see `Regis from Monica`.

Where can it come from?

**Comment by djaiss** [comment]
I have cleared the cache with `php artisan cache:clear`.

I'll monitor the emails tonight to see if it's still happening.

**Comment by djaiss** [comment]
I've finally found it.
Postmark, which is the transactional provider we use, actually overrides the FROM EMAIL ADDRESS field.

It's fixed now.

**Comment by asbiin** [comment]
Sorry ... still getting email reminder from "Regis from Monica <regis@monicahq.com>"

**Comment by djaiss** [comment]
The server rebooted last night - and now it's now `Monica HQ`.

How come this env variable was only able to change after a reboot?
